<LEXEME> ::= <KEYWORD> | <IDENT> | <OP> | <LIT_INT> | <LIT_FLOAT>
<LEXEME2> ::= <KEYWORD> | <IDENT> | <OP> | <LIT_INT> | <LIT_FLOAT>
// his is a hack to define lexemes
<OP> ::= <OP_G> | <OP_GE> | <OP_E> | <OP_L>
<KEYWORD> ::= <KW_ELIF> | <KW_ELSE> | <KW_WHILE> | <KW_IF>
<KW_IF> ::= "if"
<KW_WHILE> ::= "while"
<KW_ELIF> ::= "elif"
<KW_ELSE> ::= "else"
<OP_L> ::= "<"
<OP_G> ::= ">"
<OP_GE> ::= ">="
<OP_E> ::= "=="

<LIT_INT> ::= <DIGITS>
<LIT_FLOAT> ::= <DECIMAL_IDENTIFIER_C> <DIGITS> | <DIGITS> <DECIMAL_IDENTIFIER_C> <DIGITS>
// [.][0123456789] | [0123456789][.][0123456789][h]

// ["] [abc] ["]

<DECIMAL_IDENTIFIER_C> ::= "."

<DIGITS> ::= <DIGIT> | <DIGIT> <DIGITS>

<IDENT> ::= <LETTER> | <LETTER> <ANY_IDENT>
<ANY_IDENT> ::= <ANY_IDENT_C> | <ANY_IDENT_C> <ANY_IDENT>
<ANY_IDENT_C> ::= <LETTER> | <DIGIT>
<LETTER> ::= <L_LETTER> | <U_LETTER>
<L_LETTER> ::= "i" | "f" | "a" | "e" | "l" | "s" | "w" | "h"
<U_LETTER> ::= "A" | "B"
<DIGIT> ::= "0" | "1"
; <L_LETTER> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "_"
; <U_LETTER> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
; <DIGIT> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
